Bootstrap: docker
From: alpine:edge

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-cowsay
    COPYRIGHT Copyright © 2022 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 

%post
    apk update
    apk add cowsay=3.04
